[project]
name = "miami"

[contracts.proposal-body]
path = "contracts/proposal-body.clar"
depends_on = []

[contracts.proposal-core-v1]
path = "contracts/proposal-core-v1.clar"
depends_on = ["proposal-body"]
